---
- name: Show message
  debug:
    msg: "Test forgalaxy!"
    
- name: Add repository `Sisysphus` and remove other repositories
  community.general.apt_repo:
    repo: Sisysphus
    state: present
    remove_others: true
